name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'why this workflow is triggered'     
        required: true
        default: 'group list updated'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: curl -sSL http://aliyun.taraxacum.ink:20999/groups/json/5 > _data/all.json
      - run: curl -sSL http://aliyun.taraxacum.ink:20999/groups/json/15 > _data/groups.json
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: lemonarc/jekyll-action@1.0.0
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          SINGLE_COMMIT: true
